export const state = () => ({
  regulars: [
    "Chris Thile",
    "Serena Brook",
    "Madison Cunningham",
    "Chris Eldridge",
    "Mike Elizondo",
    "Brittany Haas",
    "Alan Hampton",
    "Greg Hess",
    "Sarah Jarosz",
    "Paul Kowert",
    "Julian Lage",
    "Holly Laurent",
    "Gaby Moreno",
    "Aoife O'Donovan",
    "Ted Poor",
    "Gabe Witcher",
    "Mike Yard",
    "Rachel Axler",
    "Patrick Clair",
    "Tom Papa",
    "Katie Rich",
    "Mark Vigeant",
    "Debra Beck",
    "Todd Behrens ",
    "Theresa Burgess",
    "Sam Hudson",
    "Janis Kaiser",
    "Ben Miller",
    "Emerald O’Brien",
    "Joey Ryan",
    "Thomas Scheuzger",
    "Kathryn Slusher",
    "Noah Smith",
    "Albert Webster",
    "Jason Colton",
    "Jeff Hnilicka",
  ]
})